/**
 * Report footer section formatter.
 */

import type { ReportData } from '../../core/types.js';

export function formatFooter(report: ReportData): string[] {
  return [
    '---',
    `*Completeness: ${report.meta.analysisCompleteness}% | Generated by codebase-analyzer v${report.meta.analyzerVersion}*`,
  ];
}
